### ISSUE TITLE
Unable to run Docker version

### ISSUE THREAD

**Issue by Thomas-Schubert** [henry-spanka/freeathome-api#17]
I'm not a Docker expert, so apologies upfront...

When running the docker version, the container exits immediately with this error (as per the log below). I'm sure I have made a stupid/beginner mistake.

Thanks for a hint to address this,

Thomas

_______________________________

internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module '/usr/src/app/dist/index.js'
Require stack:
- /usr/src/app/bin/freeathome-api
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/usr/src/app/bin/freeathome-api:13:1)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/src/app/bin/freeathome-api' ]
}

**Comment by henry-spanka** [comment]
Hi Thomas,
do you use the version-X.X.X or master (latest) image?

**Comment by henry-spanka** [comment]
I have released a new version (and a new docker image) which should fix the error you mentioned.

Please try to use the image tag `version-1.1.0`.

**Comment by Thomas-Schubert** [comment]
That did it. Thank you so much, really appreciated!
